### ISSUE TITLE
Suggestion:

### ISSUE THREAD

**Issue by frederikas** [Flashback083/Unbreed#1]
Make an config option so the breed pokemon are neutered to all but the original trainer :)

**Comment by Flashback083** [comment]
Im not sure to understand, like, the ot can breed a castrate pokemon ?

**Comment by frederikas** [comment]
Basically so that either; castration is forced if you sell or trade the pokemon 
or that breed pokemon can only be breed further on by the OT
if anything like that is even remotely possible :P

its because we like a system like this that can keep up the value of actually breeding things, but given that asfar as i understand you have to manually castrate every pokemon you breed before you sell it, there will be alot of guys that sell without castrating - and what i want/wish for is an option (maybe serverside) that can fix that :)

**Comment by Flashback083** [comment]
The issue with that is that not the main goal of the plugin
Also, you certainly want that work with GTS to make it unbreedable when player send it to GTS but it would be better to have a plugin special for that.

**Comment by frederikas** [comment]
well... guess you have a suggestion for another plugin then xD
also in the code part of this site, all i can download is a readme file saying "unbreed" is that on purpose?

**Comment by Flashback083** [comment]
for unbreed there is a link for download here https://github.com/Flashback083/Unbreed/releases
But i would suggest to come on my discord to be sure to get the latest one
https://discord.gg/BhWFTPd
